## Reto 5: Lambda

#### b) Estadísticas de población

Se ha copiado la información desde la página de INEGI de los datos de población para el año 2020 ([link](https://www.inegi.org.mx/app/tabulados/interactivos/?pxq=Poblacion_Poblacion_01_e60cd8cf-927f-4b94-823e-972457a12d4b)), pero al pegar la información se ha obtenido en forma de texto, así que se ha creado una cadena de texto multilínea y se ha guardado en la variable `estados_texto`

In [1]:
estados_texto = """
Entidad federativa	Población en 2020
Aguascalientes	1 425 607
Baja California	3 769 020
Baja California Sur	798 447
Campeche	928 363
Coahuila de Zaragoza	3 146 771
Colima	731 391
Chiapas	5 543 828
Chihuahua	3 741 869
Ciudad de México	9 209 944
Durango	1 832 650
Guanajuato	6 166 934
Guerrero	3 540 685
Hidalgo	3 082 841
Jalisco	8 348 151
México	16 992 418
Michoacán de Ocampo	4 748 846
Morelos	1 971 520
Nayarit	1 235 456
Nuevo León	5 784 442
Oaxaca	4 132 148
Puebla	6 583 278
Querétaro	2 368 467
Quintana Roo	1 857 985
San Luis Potosí	2 822 255
Sinaloa	3 026 943
Sonora	2 944 840
Tabasco	2 402 598
Tamaulipas	3 527 735
Tlaxcala	1 342 977
Veracruz de Ignacio de la Llave	8 062 579
Yucatán	2 320 898
Zacatecas	1 622 138
"""

Este reto está compuesto por varias tareas, que van desde **examinar**, **formatear**, **convertir** y **filtrar** para que se puedan obtener algunas estadísticas que se pueden encontrar en las celdas finales. Cada tarea termina con una variable con ciertos resultados que será usada por la siguiente tarea y algunas variables serán usadas en la celda final, así que manten el nombre de las variables de los resultados, entonces vamos con las tareas.

1. Dividir el texto en líneas, osea, necesitas crear una lista, donde cada elemento de la lista sea una línea del texto para ello has uso de la función `cadena.splitlines()` que toma el texto y lo segmenta regresando una lista donde cada elemento contiene cada una de las líneas. Si deseas conocer más a detalle sobre esta u otras funciones de cadenas puedes consultar la [página de la documentación oficial](https://docs.python.org/3/library/stdtypes.html#str.splitlines). El resultado guárdalo en la variable `estados_lineas`:

In [2]:
estados_lineas = estados_texto.splitlines()

estados_lineas

['',
 'Entidad federativa\tPoblación en 2020',
 'Aguascalientes\t1 425 607',
 'Baja California\t3 769 020',
 'Baja California Sur\t798 447',
 'Campeche\t928 363',
 'Coahuila de Zaragoza\t3 146 771',
 'Colima\t731 391',
 'Chiapas\t5 543 828',
 'Chihuahua\t3 741 869',
 'Ciudad de México\t9 209 944',
 'Durango\t1 832 650',
 'Guanajuato\t6 166 934',
 'Guerrero\t3 540 685',
 'Hidalgo\t3 082 841',
 'Jalisco\t8 348 151',
 'México\t16 992 418',
 'Michoacán de Ocampo\t4 748 846',
 'Morelos\t1 971 520',
 'Nayarit\t1 235 456',
 'Nuevo León\t5 784 442',
 'Oaxaca\t4 132 148',
 'Puebla\t6 583 278',
 'Querétaro\t2 368 467',
 'Quintana Roo\t1 857 985',
 'San Luis Potosí\t2 822 255',
 'Sinaloa\t3 026 943',
 'Sonora\t2 944 840',
 'Tabasco\t2 402 598',
 'Tamaulipas\t3 527 735',
 'Tlaxcala\t1 342 977',
 'Veracruz de Ignacio de la Llave\t8 062 579',
 'Yucatán\t2 320 898',
 'Zacatecas\t1 622 138']

2. Eliminar líneas en blanco, usándo el método que desees, el resultado se deberá guardar en la misma variable `estados_lineas`:

In [3]:
del estados_lineas[:2]
estados_lineas

['Aguascalientes\t1 425 607',
 'Baja California\t3 769 020',
 'Baja California Sur\t798 447',
 'Campeche\t928 363',
 'Coahuila de Zaragoza\t3 146 771',
 'Colima\t731 391',
 'Chiapas\t5 543 828',
 'Chihuahua\t3 741 869',
 'Ciudad de México\t9 209 944',
 'Durango\t1 832 650',
 'Guanajuato\t6 166 934',
 'Guerrero\t3 540 685',
 'Hidalgo\t3 082 841',
 'Jalisco\t8 348 151',
 'México\t16 992 418',
 'Michoacán de Ocampo\t4 748 846',
 'Morelos\t1 971 520',
 'Nayarit\t1 235 456',
 'Nuevo León\t5 784 442',
 'Oaxaca\t4 132 148',
 'Puebla\t6 583 278',
 'Querétaro\t2 368 467',
 'Quintana Roo\t1 857 985',
 'San Luis Potosí\t2 822 255',
 'Sinaloa\t3 026 943',
 'Sonora\t2 944 840',
 'Tabasco\t2 402 598',
 'Tamaulipas\t3 527 735',
 'Tlaxcala\t1 342 977',
 'Veracruz de Ignacio de la Llave\t8 062 579',
 'Yucatán\t2 320 898',
 'Zacatecas\t1 622 138']

3. Eliminando encabezados, debido a que la información viene de una tabla incluye los encabezados de las columnas, pero esos no son datos, así que hay que eliminarlos y el resultado se siguie guardando en la variable `estados_lineas`:

In [4]:
#Se eliminaron en la celda anterior utilizando del (aunque se pudo hacer con "pop" en ambas celdas)
estados_lineas

['Aguascalientes\t1 425 607',
 'Baja California\t3 769 020',
 'Baja California Sur\t798 447',
 'Campeche\t928 363',
 'Coahuila de Zaragoza\t3 146 771',
 'Colima\t731 391',
 'Chiapas\t5 543 828',
 'Chihuahua\t3 741 869',
 'Ciudad de México\t9 209 944',
 'Durango\t1 832 650',
 'Guanajuato\t6 166 934',
 'Guerrero\t3 540 685',
 'Hidalgo\t3 082 841',
 'Jalisco\t8 348 151',
 'México\t16 992 418',
 'Michoacán de Ocampo\t4 748 846',
 'Morelos\t1 971 520',
 'Nayarit\t1 235 456',
 'Nuevo León\t5 784 442',
 'Oaxaca\t4 132 148',
 'Puebla\t6 583 278',
 'Querétaro\t2 368 467',
 'Quintana Roo\t1 857 985',
 'San Luis Potosí\t2 822 255',
 'Sinaloa\t3 026 943',
 'Sonora\t2 944 840',
 'Tabasco\t2 402 598',
 'Tamaulipas\t3 527 735',
 'Tlaxcala\t1 342 977',
 'Veracruz de Ignacio de la Llave\t8 062 579',
 'Yucatán\t2 320 898',
 'Zacatecas\t1 622 138']


4. Separando columnas, para ello se hará uso de otra función de cadenas llamada `cadena.split(separador)`, entonces el proceso consiste en tomar un elemento de la lista que es una cadena de texto, aplicar la función `split()` para que regrese una lista de dos cadenas, el nombre del estado y el valor de la población; ésto se tiene que realizar para cada uno de los elementos, así que conviene hacer uso de `map()`, por lo tanto se necesitas crear la función de transformación `separando_columnas()`, la idea de esta función es tranformar por ejemplo `'Aguascalientes\t1 425 607' -> ['Aguascalientes', '1 425 607']`. El resultado de la función `map()` lo guardamos en la variable `estados_columnas`:

In [5]:
def separando_columnas(cadena):
    return cadena.split('\t')

In [6]:
#estados_columnas = list(map(lambda x: x.split('\t'), estados_lineas))
estados_columnas = list(map(separando_columnas, estados_lineas))
estados_columnas[:5]  # permite ver sólo los primeros 5 elementos de la lista

[['Aguascalientes', '1 425 607'],
 ['Baja California', '3 769 020'],
 ['Baja California Sur', '798 447'],
 ['Campeche', '928 363'],
 ['Coahuila de Zaragoza', '3 146 771']]

5. Convertir la columna de la cantidad de población de cadena a entero, así que hay que tomar la segunda columna de cada elemento y convertirlo a entero, aunque posiblemente la conversión no se pueda llevar acabo porque hay símbolos que no son dígitos, así que primero hay que eliminar esos símbolos (podrías usar otra función de cadenas para eso) y luego convertir a entero, así que crea otra función de transformación con el nombre `texto_a_numero()` y luego usa `map()` guardando los resultados en la variable `estados_numeros`:

In [7]:
def texto_a_numeros(estado):
    estado[1] = int(estado[1].replace(' ', ''))
    return estado

> **Tip:** Recuerda, tienes que hacer la siguiente transformación:
>
> `['Aguascalientes', '1 425 607'] -> ['Aguascalientes', 1425607]`
>    
> o sea, recibes como dato una lista de dos elementos y tienes que regresar una lista de dos elementos, sólo que el segundo elemento se convierte de cadena a entero (¡capichi!)

In [8]:
estados_numeros = list(map(texto_a_numeros, estados_columnas))

estados_numeros[:5]

[['Aguascalientes', 1425607],
 ['Baja California', 3769020],
 ['Baja California Sur', 798447],
 ['Campeche', 928363],
 ['Coahuila de Zaragoza', 3146771]]

6. Ordeando en base a la columna de población de mayor a menor, para ello tendrás que hacer uso de la función `lista.sort()` y funciones `lambda`, pero como `sort()` modifica el órden de la lista original, primero realiza una copia (usando `lista.copy()` en una nueva variable llamada `estados_mas_menos` y entonces ordena los elementos de esta variable.

In [9]:
estados_mas_menos = estados_columnas.copy()

estados_mas_menos = sorted(estados_mas_menos, key = lambda x: x[1], reverse=True)

estados_mas_menos

[['México', 16992418],
 ['Ciudad de México', 9209944],
 ['Jalisco', 8348151],
 ['Veracruz de Ignacio de la Llave', 8062579],
 ['Puebla', 6583278],
 ['Guanajuato', 6166934],
 ['Nuevo León', 5784442],
 ['Chiapas', 5543828],
 ['Michoacán de Ocampo', 4748846],
 ['Oaxaca', 4132148],
 ['Baja California', 3769020],
 ['Chihuahua', 3741869],
 ['Guerrero', 3540685],
 ['Tamaulipas', 3527735],
 ['Coahuila de Zaragoza', 3146771],
 ['Hidalgo', 3082841],
 ['Sinaloa', 3026943],
 ['Sonora', 2944840],
 ['San Luis Potosí', 2822255],
 ['Tabasco', 2402598],
 ['Querétaro', 2368467],
 ['Yucatán', 2320898],
 ['Morelos', 1971520],
 ['Quintana Roo', 1857985],
 ['Durango', 1832650],
 ['Zacatecas', 1622138],
 ['Aguascalientes', 1425607],
 ['Tlaxcala', 1342977],
 ['Nayarit', 1235456],
 ['Campeche', 928363],
 ['Baja California Sur', 798447],
 ['Colima', 731391]]

7. Obtener la lista de estados por arriba del promedio de población, para ello a continuación hay una celda que calcula el promedio, sólo ejecútala y luego entonces filtra la lista `estados_mas_menos` y el resultado guárdalo en la variable `estados_arriba_promedio`:

In [10]:
promedio = int(sum([x[1] for x in estados_mas_menos]) / len(estados_mas_menos))
promedio

3937938

In [11]:
estados_arriba_promedio = list(filter(lambda estados: estados[1] >= promedio, estados_mas_menos))

estados_arriba_promedio

[['México', 16992418],
 ['Ciudad de México', 9209944],
 ['Jalisco', 8348151],
 ['Veracruz de Ignacio de la Llave', 8062579],
 ['Puebla', 6583278],
 ['Guanajuato', 6166934],
 ['Nuevo León', 5784442],
 ['Chiapas', 5543828],
 ['Michoacán de Ocampo', 4748846],
 ['Oaxaca', 4132148]]

8. Finalmente hay que obtener la lista de estados por abajo del promedio de población, entonces filtra la lista `estados_mas_menos` y el resultado guárdalo en la variable `estados_abajo_promedio`:

In [12]:
estados_abajo_promedio = list(filter(lambda estados: estados[1] < promedio, estados_mas_menos))

estados_abajo_promedio

[['Baja California', 3769020],
 ['Chihuahua', 3741869],
 ['Guerrero', 3540685],
 ['Tamaulipas', 3527735],
 ['Coahuila de Zaragoza', 3146771],
 ['Hidalgo', 3082841],
 ['Sinaloa', 3026943],
 ['Sonora', 2944840],
 ['San Luis Potosí', 2822255],
 ['Tabasco', 2402598],
 ['Querétaro', 2368467],
 ['Yucatán', 2320898],
 ['Morelos', 1971520],
 ['Quintana Roo', 1857985],
 ['Durango', 1832650],
 ['Zacatecas', 1622138],
 ['Aguascalientes', 1425607],
 ['Tlaxcala', 1342977],
 ['Nayarit', 1235456],
 ['Campeche', 928363],
 ['Baja California Sur', 798447],
 ['Colima', 731391]]

La siguiente celda imprime algunas estadísticas usando los resultados que has obtenido, para validar tus datos pasa a la siguiente celda!

In [13]:
import numpy as np

titulo = "== Algunos datos de población de los estados de México =="
col1 = 40
col2 = 20
ancho = max(col1 + col2 + 3, len(titulo))
linea = lambda: print("-" * ancho)
print_fila = lambda d1, d2: print(f"{d1:{col1}} | {d2:>{col2}}")

print(f"\n{titulo:^{ancho}}\n")
linea()
print_fila("Variable", "Resultado")
linea()
print_fila("Población total", sum([x[1] for x in estados_numeros]))
print_fila("Estado con más población", "({}) {}".format(*estados_mas_menos[0]))
print_fila("Estado con menos población", "({}) {}".format(*estados_mas_menos[-1]))
print_fila("Población promedio", promedio)
print_fila("Núm. de estados por arriba del promedio", len(estados_arriba_promedio))
print_fila("Núm. de estados por abajo del promedio", len(estados_abajo_promedio))
linea()


   == Algunos datos de población de los estados de México ==   

---------------------------------------------------------------
Variable                                 |            Resultado
---------------------------------------------------------------
Población total                          |            126014024
Estado con más población                 |    (México) 16992418
Estado con menos población               |      (Colima) 731391
Población promedio                       |              3937938
Núm. de estados por arriba del promedio  |                   10
Núm. de estados por abajo del promedio   |                   22
---------------------------------------------------------------


Esta si es la celda de validación!

In [14]:
import numpy as np

datos = [126014024, ["México", 16992418], ["Colima", 731391], 3937938, 10, 22]
titulo = "== Datos de validación de la población de los estados de México =="
col1 = 40
col2 = 20
ancho = max(col1 + col2 + 3, len(titulo))
linea = lambda: print("-" * ancho)
print_fila = lambda d1, d2: print(f"{d1:{col1}} | {d2:>{col2}}")

print(f"\n{titulo:^{ancho}}\n")
linea()
print_fila("Variable", "Resultado esperado")
linea()
print_fila("Población total", datos[0])
print_fila("Estado con más población", "({}) {}".format(*datos[1]))
print_fila("Estado con menos población", "({}) {}".format(*datos[2]))
print_fila("Población promedio", datos[3])
print_fila("Núm. de estados por arriba del promedio", datos[4])
print_fila("Núm. de estados por abajo del promedio", datos[5])
linea()


== Datos de validación de la población de los estados de México ==

------------------------------------------------------------------
Variable                                 |   Resultado esperado
------------------------------------------------------------------
Población total                          |            126014024
Estado con más población                 |    (México) 16992418
Estado con menos población               |      (Colima) 731391
Población promedio                       |              3937938
Núm. de estados por arriba del promedio  |                   10
Núm. de estados por abajo del promedio   |                   22
------------------------------------------------------------------
